### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by ddelange** [suzil/suzil#1]
Do you have a catch-all on your domain i.e. could I send to `postmaster/admin/suzil@suzil.dev`?

**Comment by suzil** [comment]
Unfortunately no 😢 

But here's an email: https://github.com/suzil/awsstepfuncs/blob/master/setup.py#L35

**Comment by mxschmitt** [comment]
![image](https://user-images.githubusercontent.com/17984549/119564830-7f6e7480-bda9-11eb-9622-a20ff1ae7365.png)
